### ISSUE TITLE
[ENHANCEMENT] Grid size should be limited.

### ISSUE THREAD

**Issue by meadoge** [trhgquan/JBomb#17]
Sounds awful but is there anyone want to play a 100x100 grid?

We should limit the grid's size down to 8x8, 16x16 and 16x30. [Here's the link.](https://mzrg.com/js/mbm/#:~:text=Some%20notes%20on%20terminology%3A%20The,a%20mine%2C%20or%20is%20safe.)

And when I say ```limit the size```, I means we should make bombs constant, not a random variable.

**Comment by trhgquan** [comment]
Noted.
