### ISSUE TITLE
Some new fixtures, planning to do

### ISSUE THREAD

**Issue by trhgquan** [trhgquan/JBomb#9]
## Game

- [x] Add bombs defused after lost.
- [x] Add __more__ CSS to game result

## Webpage

- [ ] ~~Add favicon~~

That's all things I'm planning to do.

@meadoge

**Comment by trhgquan** [comment]
Small note for Game1. that we can use `total bombs` minus `bombs left` to get number of bombs defused.

**Comment by meadoge** [comment]
> Small note for Game1. that we can use `total bombs` minus `bombs left` to get number of bombs defused.

Actually `bombs left` does not represents the bombs defused, it is the number of times user marked into a cell.

I wrote a separate count function, so it can work properly in O(width * height), but only when the game is ended.

Regards,

**Comment by trhgquan** [comment]
> > Small note for Game1. that we can use `total bombs` minus `bombs left` to get number of bombs defused.
> 
> Actually `bombs left` does not represents the bombs defused, it is the number of times user marked into a cell.
> 
> I wrote a separate count function, so it can work properly in O(width * height), but only when the game is ended.
> 
> Regards,

My fault. Now we should look into tje CSS, how should we change it?

**Comment by trhgquan** [comment]
Issue updated with checklist.

**Comment by meadoge** [comment]
> __more__ CSS to game result

what is __more__ and how much is enough?

**Comment by trhgquan** [comment]
These are enough. Can you please create a PR and we move to our next issue?
